name: Build
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'PlcLibrary/**'
      - 'PushoverTwincatService/**' 
      - 'Example/**' 
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-plc-library:
    name: Build Pushover.library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
          workspace: "PlcLibrary"
          
      - name: Publish Unittest
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: archive/tests/**/TcUnit_xUnit_results.xml
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PlcLibrary
          path: |
            **/*library

  build-windows-service:            
    name: Build PushoverTwinpackService.exe
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Restore NuGet packages
      run: nuget restore PushoverTwincatService.sln
      working-directory: PushoverTwincatService

    - name: Build Solution
      run: msbuild PushoverTwincatService.sln /p:Configuration=Release
      working-directory: PushoverTwincatService

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PushoverTwinpackService
        path: PushoverTwincatService/PushoverTwincatService/bin/Release   
          
